name: Run Cake build
description: Template for running Cake build

inputs:
  script-path:
    description: The path to Cake script to run
  args:
    description: The arguments to pass to Cake script

outputs:
  cake-output-json:
    description: Output variables set from Cake script as JSON
    value: ${{ steps.cake-build.outcome == 'success' && toJson(steps.cake-build.outputs) || '{}' }}

runs:
  using: "composite"
  steps:
    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Get NuGet global packages directory
      id: nuget-global-packages
      shell: pwsh
      run: |
        $globalPackagesDir = (dotnet nuget locals global-packages --list) -replace 'global-packages: ', ''
        Write-Host "Global packages dir: $globalPackagesDir"
        Write-Output "path=$globalPackagesDir" >> $env:GITHUB_OUTPUT

    - name: Setup NuGet cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.nuget-global-packages.outputs.path }}
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: ${{ runner.os }}-nuget-

    - name: Restore local dotnet tools
      shell: pwsh
      run: dotnet tool restore

    - name: Run Cake build
      id: cake-build
      shell: pwsh
      run: dotnet cake ${{ inputs.script-path }} ${{ inputs.args }}
